# Generated by Django 3.2 on 2021-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=200, verbose_name='Emaili')),
                ('qayerdan', models.CharField(max_length=100, verbose_name='Qayerdan')),
                ('time', models.TimeField(max_length=70, verbose_name='Time')),
                ('date', models.DateField(max_length=80, verbose_name='Date')),
                ('qayergacha', models.CharField(max_length=100, verbose_name='Qayergacha')),
                ('message', models.CharField(max_length=50, verbose_name='Xabari')),
                ('adults', models.CharField(max_length=50)),
                ('children', models.CharField(max_length=50)),
                ('comfort', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'buyurtma',
                'verbose_name_plural': 'buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=200, verbose_name='Emaili')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('message', models.CharField(max_length=250, verbose_name='Xabari')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'Contactlar',
            },
        ),
    ]
