# Generated by Django 3.2 on 2021-05-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_system', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
