# Generated by Django 3.2 on 2021-05-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_system', '0003_remove_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Maqola', 'verbose_name_plural': 'Maqolalar'},
        ),
    ]
